export enum RepositoryEnum  {
    PRODUCT_REPOSITORY = "PROCUCT_REPOSITORY",
    CATEGORY_REPOSITORY = " CATEGORY_REPOSITORY",
    COMIDA_REPOSITORY = " COMIDA_REPOSITORY",
    CHEF_REPOSITORY = " CHEF_REPOSITORY",
}